- hosts: localhost
  vars:
    source_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  tasks:
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/dotfiles.yml

